name: WP Plugin README update
on:
  push:
    branches:
    - master
jobs:
  trunk:
    name: Push to trunk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: WP Plugin README update
      uses: 10up/action-wordpress-plugin-asset-update@develop
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        README_NAME: README.txt
